version: '3'

volumes:
  web:

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - web
    volumes:
      - ${PWD}/docker/nginx:/etc/nginx/conf.d
      - web:/usr/src/app/checkouts/readthedocs.org/static

  web:
    build:
      context: .
      dockerfile: ${PWD}/docker/Dockerfile
    volumes:
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}/docker/settings/web.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/dev.py
      - web:/usr/src/app/checkouts/readthedocs.org/static
    links:
      - database
      - redis
    environment:
      - DJANGO_SETTINGS_SKIP_LOCAL=t

  celery:
    build:
      context: .
      dockerfile: ${PWD}/docker/Dockerfile
    volumes:
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}/docker/settings/celery.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/dev.py
    links:
      - database
      - redis
    environment:
      - DJANGO_SETTINGS_SKIP_LOCAL=t
    command: ["python3", "-m", "celery", "worker", "-A", "readthedocs.worker", "-Ofair", "-c", "1", "-Q", "web,web01,reindex", "-l", "DEBUG"]

  build:
    build:
      context: .
      dockerfile: ${PWD}/docker/Dockerfile
    volumes:
      - ${PWD}:/usr/src/app/checkouts/readthedocs.org
      - ${PWD}/../readthedocs-ext:/usr/src/app/checkouts/readthedocs-ext
      - ${PWD}/docker/settings/build.py:/usr/src/app/checkouts/readthedocs.org/readthedocs/settings/dev.py

      # The python code at readthedocs/doc_builder/environments.py
      # mounts `self.project.doc_path`. We need to share this path
      # between our host, the build container, and the container that
      # is created inside the build container. Because of this, we
      # need the path in the main host.
      - /usr/src/app/checkouts/readthedocs.org/user_builds:/usr/src/app/checkouts/readthedocs.org/user_builds

      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - redis
    environment:
      - DJANGO_SETTINGS_SKIP_LOCAL=t
    command: ["python3", "-m", "celery", "worker", "-A", "readthedocs.worker", "-Ofair", "-c", "1", "-Q", "builder,celery,default,build01", "-l", "DEBUG"]

  redis:
    image: redis:3.2.7

  database:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=docs_user
      - POSTGRES_PASSWORD=docs_pwd
      - POSTGRES_DB=docs_db
